workflows:
  android:
    name: Android Build
    environment:
      flutter: stable
      android:
        image: ubuntu-java11-android-30
      groups:
        - keystore_credentials
        - google_play
      vars:
        PACKAGE_NAME: "com.methodist.youthmind"
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
        - pattern: "release*"
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Flutter analyze
        script: flutter analyze

      - name: Run Flutter tests
        script: flutter test

      - name: Build APK with Flutter
        script: |
          flutter build apk --release

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - adedejisomoye1@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal # Can be internal, alpha, beta, or production
        submit_as_draft: true
