name: youth_guide
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.4+05

environment:
  sdk: 3.7.0 <4.0.0

dependencies:
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_tts: ^4.2.2
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.2.0
  intl: ^0.20.1
  package_info_plus: ^8.3.0
  path: ^1.9.1
  percent_indicator: ^4.2.4
  provider: ^6.1.4
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.4
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/bible/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
